### ISSUE TITLE
[PENDING] Update windows installer to 1.7

### ISSUE THREAD

**Issue by sergeevabc** [QTodoTxt/QTodoTxt#378] opened 2016-12-14 15:29 UTC

**Comment by oroulet** [comment] 2016-12-14 15:33
Last version is 1.7.0. for someone using Windows it should be easy

**Comment by sergeevabc** [comment] 2016-12-14 20:12
Please, generate ```.exe``` for the rest of us who are merely users without compiler.

**Comment by oroulet** [comment] 2016-12-14 20:23
I do not have Windows.

**Comment by sergeevabc** [comment] 2016-12-14 20:26
But someone somehow generated Windows installers earlier, right?
We should restore this flow if it is broken.

**Comment by anacondaqq** [comment] 2016-12-14 20:42
There are error when trying to build 1.7.0 or even latest revision on windows 10 with WinPython 3.4.4.4

Error message:
```
Traceback (most recent call last):
  File "qtodotxt.pyw", line 30, in <module>
  File "C:\Users\admin\dev\soft\WinPython-64bit-3.4.4.4Qt5\python-3.4.4.amd64\lib\site-packages\qtodotxt\app.py", line 71, in run
    controller = _createController(args)
  File "C:\Users\admin\dev\soft\WinPython-64bit-3.4.4.4Qt5\python-3.4.4.amd64\lib\site-packages\qtodotxt\app.py", line 56, in _createController
    window = MainView()
  File "C:\Users\admin\dev\soft\WinPython-64bit-3.4.4.4Qt5\python-3.4.4.amd64\lib\site-packages\qtodotxt\ui\views\main_view.py", line 16, in __init__
    self._initUI()
  File "C:\Users\admin\dev\soft\WinPython-64bit-3.4.4.4Qt5\python-3.4.4.amd64\lib\site-packages\qtodotxt\ui\views\main_view.py", line 27, in _initUI
    css = open(cssPath, 'r', encoding='utf-8').read()
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\admin\\dev\\soft\\WinPython-64bit-3.4.4.4Qt5\\QTodoTxt-master\\packaging\\Windows\\dist\\resources\\css/default.css'

```

**Comment by oroulet** [comment] 2016-12-14 20:50
Can you run it? I think @pkev used Windows so it should work and only the
the build script should be updated.... That script is crazy complicated, it
should not  be necessary at all....

**Comment by oroulet** [comment] 2016-12-14 20:52
Btw the end looks like a hard coded path for Linux

**Comment by anacondaqq** [comment] 2016-12-14 20:54
@oroulet i trying to run it, and nothing happened, impossible to run, in APPDATA i see strerr file with the text what you see above.

**Comment by sergeevabc** [comment] 2016-12-15 20:01
Should this issue be assigned to @pkev then?

**Comment by oroulet** [comment] 2016-12-15 21:26
As always In open source world, the best thing to do is to try yourself or wait and hope

**Comment by sergeevabc** [comment] 2016-12-15 21:49
> The best thing to do is to try yourself or wait and hope

Core value of open source world besides freedom to look inside is to make life easier voluntarily.
And making life easier means doing, even with loose schedules and vague roles, not procrastination.
Otherwise project should be marked as abandoned to strangle illusory hopes for changes at birth.
Had user been able to polish reported roughness, he would be called a developer, right?
The latter role is yours, hence the badge, where is the former passion?

**Comment by jnstllng** [comment] 2016-12-31 13:00
I also tried to generate my own exe for Windows and tried that under Win10 and Win7 (both x64). I failed completely, but tried to follow what is explained under [Building QTodoTxt Binaries](https://github.com/QTodoTxt/QTodoTxt/wiki/Building-QTodoTxt-Binaries).

Right now, I am using the a local copy of the repository, and link to the _qtodotxt.pyw_. This works nicely, but is not a nice way to get it working for the _only_ user.  
Is it possible to include a more _idiot proof_ version for Windows users under [Building QTodoTxt Binaries](https://github.com/QTodoTxt/QTodoTxt/wiki/Building-QTodoTxt-Binaries)?

I really would like to help more in the future, but I am an absolut coding beginner.

**Comment by oroulet** [comment] 2017-01-01 08:57
> but I am an absolut coding beginner.

No problem. If you try you will get good very soon. I can help you if you
have questions. Try to google for something like ' python setup.py make
Windows installer' generating installer should not be as complicated as
what is written there. I will have a look when I get two minutes but i have
too many projects...

**Comment by oroulet** [comment] 2017-01-01 16:49
@anacondaqq I just pushed a theoretical fix to the crash above. Can you test? are there other issues on windows? https://github.com/QTodoTxt/QTodoTxt/commit/f3fdc99c2a0e7959c0376e3691aa4d264fd0259b

**Comment by anacondaqq** [comment] 2017-01-01 21:51
# tl;tr
Need someone which know python and has windows to make qtodotxt work, because it's broken on windows, and impossible to build and run it. Need to fix it asap.

# Details

@oroulet i have spent around 4-5 hours after your message to make it work, but no, no success at all.
Latest Qtodotxt impossible to build with WinPython

Here is output when trying to build with:
setup.py should be rewrited. Because it's very outdated, i saw setup.py for linux / mac, it's much better then windows one.


> python.exe setup.py py2exe

Here is output of errors! Please note at the same time 4f387cef0939b45423c77a43f9284a5b1381f7b6 hash works pretty good (possible to build with python.exe setup.py py2exe without any errors), and run files. But since this date impossible to even build new version of qtodotxt.

Btw, at the same time while impossible to build qtodotxt, it's possible to run with python bin/qtodotxt.piw

![](http://i.imgur.com/KCq5wxl.png)



```
C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\QTodoTxt-master\packaging\Windows>python.exe setup.py py2exe
running py2exe
running build_py
creating C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\QTodoTxt-master\packaging\Windows\build
creating C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\QTodoTxt-master\packaging\Windows\build\lib
creating C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\QTodoTxt-master\packaging\Windows\build\lib\qtodotxt
copying qtodotxt\app.py -> C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\QTodoTxt-master\packaging\Windows\build\lib\qtodotxt
copying qtodotxt\__init__.py -> C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\QTodoTxt-master\packaging\Windows\build\lib\qtodotxt
creating C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\QTodoTxt-master\packaging\Windows\build\lib\qtodotxt\lib
copying qtodotxt\lib\file.py -> C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\QTodoTxt-master\packaging\Windows\build\lib\qtodotxt\lib
copying qtodotxt\lib\filters.py -> C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\QTodoTxt-master\packaging\Windows\build\lib\qtodotxt\lib
copying qtodotxt\lib\tasklib.py -> C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\QTodoTxt-master\packaging\Windows\build\lib\qtodotxt\lib
copying qtodotxt\lib\task_htmlizer.py -> C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\QTodoTxt-master\packaging\Windows\build\lib\qtodotxt\lib
copying qtodotxt\lib\tendo_singleton.py -> C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\QTodoTxt-master\packaging\Windows\build\lib\qtodotxt\lib
copying qtodotxt\lib\__init__.py -> C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\QTodoTxt-master\packaging\Windows\build\lib\qtodotxt\lib
creating C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\QTodoTxt-master\packaging\Windows\build\lib\qtodotxt\test
copying qtodotxt\test\run-coverage.py -> C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\QTodoTxt-master\packaging\Windows\build\lib\qtodotxt\test
copying qtodotxt\test\run-doctests.py -> C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\QTodoTxt-master\packaging\Windows\build\lib\qtodotxt\test
copying qtodotxt\test\test_dates.py -> C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\QTodoTxt-master\packaging\Windows\build\lib\qtodotxt\test
copying qtodotxt\test\test_file.py -> C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\QTodoTxt-master\packaging\Windows\build\lib\qtodotxt\test
copying qtodotxt\test\test_filters_tree_controller.py -> C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\QTodoTxt-master\packaging\Windows\build\lib\qtodotxt\test
copying qtodotxt\test\test_htmlizer.py -> C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\QTodoTxt-master\packaging\Windows\build\lib\qtodotxt\test
copying qtodotxt\test\test_tasks.py -> C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\QTodoTxt-master\packaging\Windows\build\lib\qtodotxt\test
copying qtodotxt\test\__init__.py -> C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\QTodoTxt-master\packaging\Windows\build\lib\qtodotxt\test
creating C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\QTodoTxt-master\packaging\Windows\build\lib\qtodotxt\ui
copying qtodotxt\ui\resource_manager.py -> C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\QTodoTxt-master\packaging\Windows\build\lib\qtodotxt\ui
copying qtodotxt\ui\__init__.py -> C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\QTodoTxt-master\packaging\Windows\build\lib\qtodotxt\ui
creating C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\QTodoTxt-master\packaging\Windows\build\lib\qtodotxt\ui\controllers
copying qtodotxt\ui\controllers\filters_tree_controller.py -> C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\QTodoTxt-master\packaging\Windows\build\lib\qtodotxt\ui\controllers
copying qtodotxt\ui\controllers\main_controller.py -> C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\QTodoTxt-master\packaging\Windows\build\lib\qtodotxt\ui\controllers
copying qtodotxt\ui\controllers\menu_controller.py -> C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\QTodoTxt-master\packaging\Windows\build\lib\qtodotxt\ui\controllers
copying qtodotxt\ui\controllers\tasks_list_controller.py -> C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\QTodoTxt-master\packaging\Windows\build\lib\qtodotxt\ui\controllers
copying qtodotxt\ui\controllers\__init__.py -> C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\QTodoTxt-master\packaging\Windows\build\lib\qtodotxt\ui\controllers
creating C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\QTodoTxt-master\packaging\Windows\build\lib\qtodotxt\ui\dialogs
copying qtodotxt\ui\dialogs\about_dialog.py -> C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\QTodoTxt-master\packaging\Windows\build\lib\qtodotxt\ui\dialogs
copying qtodotxt\ui\dialogs\misc_dialogs.py -> C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\QTodoTxt-master\packaging\Windows\build\lib\qtodotxt\ui\dialogs
copying qtodotxt\ui\dialogs\settings.py -> C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\QTodoTxt-master\packaging\Windows\build\lib\qtodotxt\ui\dialogs
copying qtodotxt\ui\dialogs\settingsui.py -> C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\QTodoTxt-master\packaging\Windows\build\lib\qtodotxt\ui\dialogs
copying qtodotxt\ui\dialogs\shortcuts.py -> C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\QTodoTxt-master\packaging\Windows\build\lib\qtodotxt\ui\dialogs
copying qtodotxt\ui\dialogs\shortcutsui.py -> C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\QTodoTxt-master\packaging\Windows\build\lib\qtodotxt\ui\dialogs
copying qtodotxt\ui\dialogs\taskeditor.py -> C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\QTodoTxt-master\packaging\Windows\build\lib\qtodotxt\ui\dialogs
copying qtodotxt\ui\dialogs\taskeditor_dialog.py -> C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\QTodoTxt-master\packaging\Windows\build\lib\qtodotxt\ui\dialogs
copying qtodotxt\ui\dialogs\taskeditor_lineedit.py -> C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\QTodoTxt-master\packaging\Windows\build\lib\qtodotxt\ui\dialogs
copying qtodotxt\ui\dialogs\__init__.py -> C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\QTodoTxt-master\packaging\Windows\build\lib\qtodotxt\ui\dialogs
creating C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\QTodoTxt-master\packaging\Windows\build\lib\qtodotxt\ui\views
copying qtodotxt\ui\views\filters_tree_view.py -> C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\QTodoTxt-master\packaging\Windows\build\lib\qtodotxt\ui\views
copying qtodotxt\ui\views\main_view.py -> C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\QTodoTxt-master\packaging\Windows\build\lib\qtodotxt\ui\views
copying qtodotxt\ui\views\tasks_list_view.py -> C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\QTodoTxt-master\packaging\Windows\build\lib\qtodotxt\ui\views
copying qtodotxt\ui\views\tasks_search_view.py -> C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\QTodoTxt-master\packaging\Windows\build\lib\qtodotxt\ui\views
copying qtodotxt\ui\views\tasks_view.py -> C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\QTodoTxt-master\packaging\Windows\build\lib\qtodotxt\ui\views
copying qtodotxt\ui\views\__init__.py -> C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\QTodoTxt-master\packaging\Windows\build\lib\qtodotxt\ui\views
Traceback (most recent call last):
  File "setup.py", line 84, in <module>
  File "C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\python-3.4.4\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\python-3.4.4\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\python-3.4.4\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\python-3.4.4\lib\site-packages\py2exe\distutils_buildexe.py", line 188, in run
    self._run()
  File "C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\python-3.4.4\lib\site-packages\py2exe\distutils_buildexe.py", line 267, in _run
    builder.analyze()
  File "C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\python-3.4.4\lib\site-packages\py2exe\runtime.py", line 173, in analyze
    target.analyze(mf)
  File "C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\python-3.4.4\lib\site-packages\py2exe\runtime.py", line 74, in analyze
    modulefinder.run_script(self.script)
  File "C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\python-3.4.4\lib\site-packages\py2exe\mf3.py", line 86, in run_script
    self._scan_code(mod.__code__, mod)
  File "C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\python-3.4.4\lib\site-packages\py2exe\mf3.py", line 394, in _scan_code
    self.safe_import_hook(name, mod, fromlist, level)
  File "C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\python-3.4.4\lib\site-packages\py2exe\mf3.py", line 138, in safe_import_hook
    self.import_hook(name, caller, fromlist, level)
  File "C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\python-3.4.4\lib\site-packages\py2exe\mf3.py", line 125, in import_hook
    self._handle_fromlist(module, fromlist, caller)
  File "C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\python-3.4.4\lib\site-packages\py2exe\mf3.py", line 196, in _handle_fromlist
    self._gcd_import('{}.{}'.format(mod.__name__, x))
  File "C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\python-3.4.4\lib\site-packages\py2exe\mf3.py", line 274, in _gcd_import
    return self._find_and_load(name)
  File "C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\python-3.4.4\lib\site-packages\py2exe\mf3.py", line 357, in _find_and_load
    self._scan_code(module.__code__, module)
  File "C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\python-3.4.4\lib\site-packages\py2exe\mf3.py", line 394, in _scan_code
    self.safe_import_hook(name, mod, fromlist, level)
  File "C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\python-3.4.4\lib\site-packages\py2exe\mf3.py", line 138, in safe_import_hook
    self.import_hook(name, caller, fromlist, level)
  File "C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\python-3.4.4\lib\site-packages\py2exe\mf3.py", line 120, in import_hook
    module = self._gcd_import(name)
  File "C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\python-3.4.4\lib\site-packages\py2exe\mf3.py", line 274, in _gcd_import
    return self._find_and_load(name)
  File "C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\python-3.4.4\lib\site-packages\py2exe\mf3.py", line 288, in _find_and_load
    self._gcd_import(parent)
  File "C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\python-3.4.4\lib\site-packages\py2exe\mf3.py", line 274, in _gcd_import
    return self._find_and_load(name)
  File "C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\python-3.4.4\lib\site-packages\py2exe\mf3.py", line 318, in _find_and_load
    loader = importlib.find_loader(name, path)
  File "C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\python-3.4.4\lib\importlib\__init__.py", line 78, in find_loader
    spec = _bootstrap._find_spec(name, path)
  File "<frozen importlib._bootstrap>", line 2164, in _find_spec
  File "<frozen importlib._bootstrap>", line 1949, in find_spec
  File "<frozen importlib._bootstrap>", line 1756, in __init__
  File "<frozen importlib._bootstrap>", line 1771, in _get_parent_path
KeyError: 'qtodotxt.ui'

C:\Users\admin\dev\soft\python\WinPython-32bit-3.4.4.5Qt5\QTodoTxt-master\packaging\Windows>
```

**Comment by oroulet** [comment] 2017-01-04 19:22
@anacondaqq I confirmed what you wrote. I can run qtodotxt on windows bu the installer stuff seems broken and setup.py is very comlpicated. I have no idea how to fix it....

**Comment by PKEv** [comment] 2017-01-09 07:12
look my pull 
as I understand it at the moment py2exe does not support version 3.5 and there is no solution
(I transferred the files to compile resources and in principle it should work)

**Comment by oroulet** [comment] 2017-01-09 07:50
Do we have a solution to make a windows msi without py2exe? Anyway if py2exe does not work with 3.5 we use 3.4 to make a windows installer until they update py2exe to 3.5

**Comment by anacondaqq** [comment] 2017-01-09 08:12
thank you very much for fix. Works pretty well (tested many features, and works fine, but maybe i something miss, anyway still pretty stable).

![](http://i.imgur.com/ewfQMoR.png) 
Here is a link for 1.7.0 windows version build (builded with ISS script). 

## Download 
#### [mega](https://mega.nz/#!85IC1CrY!o7oeKkn1F3_ucYbGFFD4_O4nTvCM2vX6ASM8VJ6hGOA) 14.44MB size
#### [dropbox](https://www.dropbox.com/s/mamhors0j171omk/qtodotxt_1.7.0.exe?dl=0) 14.44MB size

## Technical Details

Latest master hash: f3fdc99c2a0e7959c0376e3691aa4d264fd0259b + merged current PR
While building - no errors or warnings. Pretty fine works. All what have i did -> it's i changed numbers of old 1.6.1 version in iss script to actual 1.7.0

Tested on Win10 x64 v1607

Thx again 👍

**Comment by oroulet** [comment] 2017-01-09 09:08
Great! I uploaded the file and updated the README!! Thanks all!

**Comment by jnstllng** [comment] 2017-01-09 13:59
This is helpful and great news! I will now use this build on Win7 x64 and Win10 x64 and will give feedback if I find anything crucial.

Thanks a lot...

**Closed** 2017-01-10 20:18 UTC
